# -*- coding: utf-8 -*-
"""sklearn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ayFX0aqgSNFtY7nDiAuJcVF-goSkwC_-
"""

from sklearn.datasets import load_iris
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold 
from sklearn.metrics import mean_squared_error
import numpy as np

iris = load_iris()

x, y = iris.data, iris.target

kf = KFold(n_splits=5, shuffle=True, random_state=42)

model = LinearRegression()

scores = []
for train_index, test_index in kf.split(x):
  x_train, x_test = x[train_index], x[test_index]
  y_train, y_test = y[train_index], y[test_index]

  model.fit(x_train, y_train)

  y_pred = model.predict(x_test)
  score = mean_squared_error(y_test, y_pred)
  scores.append(score)

mean_score = np.mean(scores)

print("K fold cross validation resul: ", scores)
print("MSE", mean_score)